# Generated by Django 5.2.7 on 2025-10-07 01:07

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=200, verbose_name='Nome da Escola')),
                ('endereco', models.TextField(blank=True, verbose_name='Endereço')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escola/', verbose_name='Logo da Escola')),
                ('template_confirmacao_inscricao', models.TextField(default='CONFIRMAÇÃO DE INSCRIÇÃO\n\nNome: {nome}\nCurso: {curso}\nNúmero de Inscrição: {numero}\nData: {data}', help_text='Use {nome}, {curso}, {numero}, {data} para campos dinâmicos', verbose_name='Template de Confirmação de Inscrição')),
            ],
            options={
                'verbose_name': 'Configuração da Escola',
                'verbose_name_plural': 'Configurações da Escola',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Curso')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('vagas', models.PositiveIntegerField(verbose_name='Número de Vagas')),
                ('nota_minima', models.DecimalField(decimal_places=2, default=10.0, max_digits=4, validators=[django.core.validators.MinValueValidator(10.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Nota Mínima para Aprovação')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('numero_estudante', models.CharField(max_length=20, unique=True, verbose_name='Número de Estudante')),
                ('bilhete_identidade', models.CharField(max_length=50, verbose_name='Bilhete de Identidade')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('data_matricula', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Matrícula')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Disciplina')),
                ('carga_horaria', models.PositiveIntegerField(default=40, verbose_name='Carga Horária (horas)')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinas', to='core.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Disciplina',
                'verbose_name_plural': 'Disciplinas',
                'ordering': ['curso', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_inscricao', models.CharField(max_length=20, unique=True, verbose_name='Número de Inscrição')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('bilhete_identidade', models.CharField(max_length=50, verbose_name='Bilhete de Identidade')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('nota_teste', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Nota do Teste (0-20)')),
                ('aprovado', models.BooleanField(default=False, verbose_name='Aprovado')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inscrição')),
                ('data_resultado', models.DateTimeField(blank=True, null=True, verbose_name='Data do Resultado')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-data_inscricao'],
            },
        ),
        migrations.CreateModel(
            name='Pai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('bilhete_identidade', models.CharField(max_length=50, verbose_name='Bilhete de Identidade')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco (Pai, Mãe, Tutor, etc.)')),
                ('alunos', models.ManyToManyField(related_name='pais', to='core.aluno', verbose_name='Alunos')),
            ],
            options={
                'verbose_name': 'Pai/Responsável',
                'verbose_name_plural': 'Pais/Responsáveis',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('bilhete_identidade', models.CharField(max_length=50, verbose_name='Bilhete de Identidade')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='Sexo')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('endereco', models.TextField(verbose_name='Endereço')),
                ('especialidade', models.CharField(max_length=200, verbose_name='Especialidade')),
                ('data_contratacao', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Contratação')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professores',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da Turma')),
                ('ano_letivo', models.CharField(max_length=9, verbose_name='Ano Letivo (ex: 2024/2025)')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='core.curso', verbose_name='Curso')),
                ('professor_titular', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor', verbose_name='Professor Titular')),
            ],
            options={
                'verbose_name': 'Turma',
                'verbose_name_plural': 'Turmas',
                'ordering': ['ano_letivo', 'nome'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos', to='core.turma', verbose_name='Turma'),
        ),
    ]
