# Generated by Django 5.2.7 on 2025-10-07 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscricao',
            name='numero_inscricao',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de Inscrição'),
        ),
    ]
