# Generated by Django 5.2.7 on 2025-10-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_inscricao_numero_inscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='ano_conclusao',
            field=models.CharField(default='2024', max_length=4, verbose_name='Ano de Conclusão'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='certificados_obtidos',
            field=models.TextField(blank=True, default='', verbose_name='Certificados/Diplomas Obtidos'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='comprovativo_pagamento',
            field=models.FileField(blank=True, null=True, upload_to='inscricoes/pagamentos/', verbose_name='Comprovativo de Pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='doc_bi',
            field=models.FileField(blank=True, null=True, upload_to='inscricoes/documentos/', verbose_name='Cópia do BI/Passaporte'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='doc_boletim',
            field=models.FileField(blank=True, null=True, upload_to='inscricoes/documentos/', verbose_name='Boletim de Notas'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='doc_certificado',
            field=models.FileField(blank=True, null=True, upload_to='inscricoes/documentos/', verbose_name='Certificado de Conclusão'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='doc_comprovativo_residencia',
            field=models.FileField(blank=True, null=True, upload_to='inscricoes/documentos/', verbose_name='Comprovativo de Residência'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='doc_fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='inscricoes/fotos/', verbose_name='Fotografia Tipo Passe'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='encarregado_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email do Encarregado'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='encarregado_local_trabalho',
            field=models.CharField(blank=True, max_length=200, verbose_name='Local de Trabalho do Encarregado'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='encarregado_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Encarregado de Educação'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='encarregado_parentesco',
            field=models.CharField(blank=True, max_length=100, verbose_name='Grau de Parentesco'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='encarregado_profissao',
            field=models.CharField(blank=True, max_length=200, verbose_name='Profissão do Encarregado'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='encarregado_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Encarregado'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='estado_civil',
            field=models.CharField(choices=[('S', 'Solteiro(a)'), ('C', 'Casado(a)'), ('D', 'Divorciado(a)'), ('V', 'Viúvo(a)')], default='S', max_length=1, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='historico_escolar',
            field=models.TextField(blank=True, default='', verbose_name='Notas/Histórico Escolar'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='local_nascimento',
            field=models.CharField(default='Luanda', max_length=200, verbose_name='Local de Nascimento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='nacionalidade',
            field=models.CharField(default='Angolana', max_length=100, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_financeiro_nome',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome do Responsável Financeiro'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_financeiro_relacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Relação com o Estudante'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='responsavel_financeiro_telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone do Responsável Financeiro'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='turno_preferencial',
            field=models.CharField(choices=[('M', 'Manhã'), ('T', 'Tarde'), ('N', 'Noite')], default='M', max_length=1, verbose_name='Turno Preferencial'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='ultima_escola',
            field=models.CharField(default='', max_length=200, verbose_name='Última Escola Frequentada'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='endereco',
            field=models.TextField(verbose_name='Endereço Completo'),
        ),
    ]
