# Generated by Django 5.2.7 on 2025-10-07 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inscricao_ano_conclusao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300, unique=True, verbose_name='Nome da Escola')),
                ('municipio', models.CharField(blank=True, max_length=100, verbose_name='Município')),
                ('provincia', models.CharField(blank=True, max_length=100, verbose_name='Província')),
                ('tipo', models.CharField(choices=[('Pública', 'Pública'), ('Privada', 'Privada')], default='Pública', max_length=20, verbose_name='Tipo')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
                'ordering': ['nome'],
            },
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='comprovativo_pagamento',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='doc_bi',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='doc_boletim',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='doc_certificado',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='doc_comprovativo_residencia',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='doc_fotografia',
        ),
        migrations.RemoveField(
            model_name='inscricao',
            name='ultima_escola',
        ),
        migrations.AddField(
            model_name='inscricao',
            name='data_validade_bi',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Validade do BI'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='numero_comprovante',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número do Comprovante/Boleto'),
        ),
        migrations.AlterField(
            model_name='inscricao',
            name='bilhete_identidade',
            field=models.CharField(max_length=50, verbose_name='Número do Bilhete de Identidade'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='escola',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to='core.escola', verbose_name='Última Escola Frequentada'),
        ),
    ]
