# Generated by Django 5.2.7 on 2025-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_escola_remove_inscricao_comprovativo_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_inicio', models.IntegerField(verbose_name='Ano de Início')),
                ('ano_fim', models.IntegerField(verbose_name='Ano de Fim')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ano Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ano Acadêmico',
                'verbose_name_plural': 'Anos Acadêmicos',
                'ordering': ['-ano_inicio'],
                'unique_together': {('ano_inicio', 'ano_fim')},
            },
        ),
    ]
