# Generated by Django 5.2.7 on 2025-10-07 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_anoacademico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('mensagem', models.TextField(verbose_name='Mensagem')),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('aviso', 'Aviso'), ('urgente', 'Urgente'), ('sucesso', 'Sucesso')], default='info', max_length=20, verbose_name='Tipo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('global_notificacao', models.BooleanField(default=False, help_text='Se marcado, todos os usuários verão esta notificação', verbose_name='Notificação Global')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='notificacoes', to=settings.AUTH_USER_MODEL, verbose_name='Destinatários')),
                ('lida_por', models.ManyToManyField(blank=True, related_name='notificacoes_lidas', to=settings.AUTH_USER_MODEL, verbose_name='Lida por')),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_acesso', models.CharField(choices=[('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('professor', 'Professor'), ('coordenador', 'Coordenador'), ('aluno', 'Aluno')], default='aluno', max_length=20, verbose_name='Nível de Acesso')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/', verbose_name='Foto')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
                'ordering': ['user__username'],
            },
        ),
    ]
