# Generated by Django 5.2.7 on 2025-10-07 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notificacao_perfilusuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_escola', models.CharField(max_length=200, unique=True, verbose_name='Nome da Escola')),
                ('plano', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Plano')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_expiracao', models.DateField(verbose_name='Data de Expiração')),
                ('estado', models.CharField(choices=[('ativo', 'Ativo'), ('expirado', 'Expirado'), ('cancelado', 'Cancelado'), ('teste', 'Período de Teste')], default='teste', max_length=20, verbose_name='Estado')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor Pago')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Subscrição',
                'verbose_name_plural': 'Subscrições',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
