# Generated by Django 5.2.7 on 2025-10-07 03:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoSubscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plano_escolhido', models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensal', max_length=20, verbose_name='Plano Escolhido')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('comprovante', models.FileField(upload_to='comprovantes/', verbose_name='Comprovante de Pagamento')),
                ('numero_referencia', models.CharField(blank=True, max_length=100, verbose_name='Número de Referência')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado')], default='pendente', max_length=20, verbose_name='Status')),
                ('data_pagamento', models.DateField(verbose_name='Data do Pagamento')),
                ('data_submissao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Submissão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('data_aprovacao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Aprovação')),
                ('recibo_pdf', models.FileField(blank=True, null=True, upload_to='recibos/', verbose_name='Recibo PDF')),
                ('aprovado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_aprovados', to=settings.AUTH_USER_MODEL, verbose_name='Aprovado Por')),
                ('subscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.subscricao', verbose_name='Subscrição')),
            ],
            options={
                'verbose_name': 'Pagamento de Subscrição',
                'verbose_name_plural': 'Pagamentos de Subscrição',
                'ordering': ['-data_submissao'],
            },
        ),
    ]
