# Generated by Django 5.2.7 on 2025-10-07 04:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_pagamentosubscricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecuperacaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('email', 'Email'), ('telefone', 'Telefone')], max_length=20, verbose_name='Tipo de Recuperação')),
                ('codigo_otp', models.CharField(blank=True, max_length=6, verbose_name='Código OTP')),
                ('token', models.CharField(blank=True, max_length=100, verbose_name='Token de Recuperação')),
                ('email_enviado', models.EmailField(blank=True, max_length=254, verbose_name='Email Enviado Para')),
                ('telefone_enviado', models.CharField(blank=True, max_length=20, verbose_name='Telefone Enviado Para')),
                ('usado', models.BooleanField(default=False, verbose_name='Usado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_expiracao', models.DateTimeField(verbose_name='Data de Expiração')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recuperacoes_senha', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Recuperação de Senha',
                'verbose_name_plural': 'Recuperações de Senha',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
