# Generated by Django 5.2.7 on 2025-10-07 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_recuperacaosenha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('professor', 'Professor'), ('coordenador', 'Coordenador'), ('aluno', 'Aluno')], default='pendente', max_length=20, verbose_name='Nível de Acesso'),
        ),
    ]
