# Generated by Django 5.2.7 on 2025-12-24 16:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_perfilusuario_nivel_acesso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título do Documento')),
                ('secao', models.CharField(choices=[('inscricao', 'Inscrição'), ('certificado', 'Certificado'), ('declaracao', 'Declaração'), ('atestado', 'Atestado'), ('diploma', 'Diploma'), ('historico', 'Histórico Escolar'), ('recibo', 'Recibo'), ('convite', 'Convite'), ('outra', 'Outra')], default='outra', max_length=50, verbose_name='Seção/Módulo')),
                ('conteudo', models.TextField(help_text='Use variáveis como {nome}, {bilhete_identidade}, {email}, {telefone}, {data_nascimento}, {curso}, {numero_inscricao}, {data_inscricao}, {data_hoje}, {nome_escola}, etc.', verbose_name='Conteúdo do Documento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
