# Generated by Django 5.2.7 on 2025-12-24 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='codigo',
            field=models.CharField(default='CURSO', max_length=50, unique=True, verbose_name='Código do Curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='duracao_meses',
            field=models.PositiveIntegerField(choices=[(3, '3 meses'), (6, '6 meses'), (12, '1 ano'), (24, '2 anos'), (36, '3 anos'), (48, '4 anos')], default=12, verbose_name='Duração'),
        ),
    ]
