# Generated by Django 5.2.7 on 2025-12-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_curso_codigo_curso_data_atualizacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='duracao_meses',
            field=models.PositiveIntegerField(choices=[(3, '3 meses'), (6, '6 meses'), (12, '1 ano'), (24, '2 anos'), (36, '3 anos'), (48, '4 anos'), (60, '5 anos')], default=12, verbose_name='Duração'),
        ),
    ]
