# Generated by Django 5.2.7 on 2025-12-25 07:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_curso_duracao_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='requer_prerequisitos',
            field=models.BooleanField(default=False, verbose_name='Requer Pré-requisitos'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='codigo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Código da Disciplina'),
        ),
        migrations.CreateModel(
            name='HistoricoAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('inscricao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historico_academico', to='core.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Histórico Académico',
                'verbose_name_plural': 'Históricos Académicos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='NotaDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Nota')),
                ('ano_conclusao', models.PositiveIntegerField(verbose_name='Ano de Conclusão')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.disciplina', verbose_name='Disciplina')),
                ('historico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_disciplina', to='core.historicoacademico', verbose_name='Histórico')),
            ],
            options={
                'verbose_name': 'Nota de Disciplina',
                'verbose_name_plural': 'Notas de Disciplina',
                'ordering': ['-ano_conclusao', 'disciplina'],
                'unique_together': {('historico', 'disciplina')},
            },
        ),
        migrations.CreateModel(
            name='PrerequisitoDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_minima_prerequisito', models.DecimalField(decimal_places=2, default=12.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)], verbose_name='Nota Mínima Necessária')),
                ('obrigatorio', models.BooleanField(default=True, verbose_name='Obrigatório')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisitos', to='core.curso', verbose_name='Curso')),
                ('disciplina_prerequisito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.disciplina', verbose_name='Disciplina Pré-requisito')),
            ],
            options={
                'verbose_name': 'Pré-requisito de Disciplina',
                'verbose_name_plural': 'Pré-requisitos de Disciplina',
                'ordering': ['curso', 'ordem'],
                'unique_together': {('curso', 'disciplina_prerequisito')},
            },
        ),
    ]
