# Generated by Django 5.2.7 on 2025-12-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_curso_requer_prerequisitos_disciplina_codigo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anoacademico',
            options={'ordering': ['-ano_inicio'], 'verbose_name': 'Ano Académico', 'verbose_name_plural': 'Anos Académicos'},
        ),
        migrations.AddField(
            model_name='anoacademico',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='ativo', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='anoacademico',
            name='ativo',
            field=models.BooleanField(default=False, verbose_name='Ano Atual'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='nivel_acesso',
            field=models.CharField(choices=[('pendente', 'Pendente de Aprovação'), ('super_admin', 'Super Administrador'), ('admin', 'Administrador'), ('secretaria', 'Secretaria'), ('secretario_academico', 'Secretário Académico'), ('daac', 'Chefe de Departamento para Assuntos Académico (DAAC)'), ('financeiro', 'Responsável Financeiro'), ('bibliotecario', 'Bibliotecário'), ('rh', 'Gestor de Recursos Humanos'), ('professor', 'Docente (Professor)'), ('coordenador', 'Coordenador'), ('aluno', 'Aluno')], default='pendente', max_length=20, verbose_name='Nível de Acesso'),
        ),
    ]
