# Generated by Django 5.2.7 on 2025-12-27 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_anoacademico_options_anoacademico_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('1', '1º Semestre'), ('2', '2º Semestre')], max_length=20, verbose_name='Semestre')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=False, verbose_name='Semestre Atual')),
                ('ano_academico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestres', to='core.anoacademico', verbose_name='Ano Académico')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'ordering': ['ano_academico', 'nome'],
                'unique_together': {('ano_academico', 'nome')},
            },
        ),
    ]
