from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from core import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index_redirect, name='index_redirect'),
    path('index/', views.index, name='index'),
    path('cursos/', views.cursos_lista, name='cursos_lista'),
    path('cursos/novo/', views.curso_create, name='curso_create'),
    path('cursos/<int:curso_id>/editar/', views.curso_edit, name='curso_edit'),
    path('cursos/<int:curso_id>/toggle/', views.curso_toggle, name='curso_toggle'),
    path('admissao/', views.admissao_estudantes, name='admissao_estudantes'),
    path('admissao/inscricao/', views.admissao_inscricao, name='admissao_inscricao'),
    path('inscricao/<int:curso_id>/', views.inscricao_create, name='inscricao_create'),
    path('inscricao/consulta/<str:numero>/', views.inscricao_consulta, name='inscricao_consulta'),
    path('inscricao/buscar/', views.inscricao_buscar, name='inscricao_buscar'),
    path('inscricao/pdf/<str:numero>/', views.gerar_pdf_confirmacao, name='gerar_pdf'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('painel/', views.painel_principal, name='painel_principal'),
    path('trocar-ano/', views.trocar_ano, name='trocar_ano'),
    path('perfil/', views.perfil_usuario, name='perfil_usuario'),
    path('avisos/', views.quadro_avisos, name='quadro_avisos'),
    path('cursos-disciplinas/', views.cursos_disciplinas, name='cursos_disciplinas'),
    path('grelha-curricular/', views.grelha_curricular, name='grelha_curricular'),
    path('cronograma-academico/', views.cronograma_academico, name='cronograma_academico'),
    path('periodo-letivo/', views.periodo_letivo, name='periodo_letivo'),
    path('horarios/', views.horarios, name='horarios'),
    path('titulos-academicos/', views.titulos_academicos, name='titulos_academicos'),
    path('modelo-avaliacao/', views.modelo_avaliacao, name='modelo_avaliacao'),
    path('syllabus/', views.syllabus, name='syllabus'),
    path('gestao-estudantes/', views.gestao_estudantes, name='gestao_estudantes'),
    path('admissao-view/', views.admissao, name='admissao'),
    path('matricula/', views.matricula, name='matricula'),
    path('lista-estudantes/', views.lista_estudantes, name='lista_estudantes'),
    path('assiduidade/', views.assiduidade, name='assiduidade'),
    path('certificados/', views.certificados, name='certificados'),
    path('historico/', views.historico, name='historico'),
    path('materiais/', views.materiais, name='materiais'),
    path('solicitacao-docs/', views.solicitacao_docs, name='solicitacao_docs'),
    path('atividades-extracurriculares/', views.atividades_extracurriculares, name='atividades_extracurriculares'),
    path('gestao-docentes/', views.gestao_docentes, name='gestao_docentes'),
    path('cadastro-professores/', views.cadastro_professores, name='cadastro_professores'),
    path('atribuicao-turmas/', views.atribuicao_turmas, name='atribuicao_turmas'),
    path('assiduidade-docentes/', views.assiduidade_docentes, name='assiduidade_docentes'),
    path('gestao-licencas/', views.gestao_licencas, name='gestao_licencas'),
    path('avaliacao-desempenho/', views.avaliacao_desempenho, name='avaliacao_desempenho'),
    path('gestao-administrativa/', views.gestao_administrativa, name='gestao_administrativa'),
    path('painel-admin/', views.painel_admin, name='painel_admin'),
    path('recursos-humanos/', views.recursos_humanos, name='recursos_humanos'),
    path('departamentos/', views.departamentos, name='departamentos'),
    path('recrutamento/', views.recrutamento, name='recrutamento'),
    path('gestao-tarefas/', views.gestao_tarefas, name='gestao_tarefas'),
    path('gestao-eventos/', views.gestao_eventos, name='gestao_eventos'),
    path('gestao-financeira/', views.gestao_financeira, name='gestao_financeira'),
    path('faturas-pagamentos/', views.faturas_pagamentos, name='faturas_pagamentos'),
    path('relatorios-financeiros/', views.relatorios_financeiros, name='relatorios_financeiros'),
    path('gestao-despesas/', views.gestao_despesas, name='gestao_despesas'),
    path('bolsas-beneficios/', views.bolsas_beneficios, name='bolsas_beneficios'),
    path('pagamento-online/', views.pagamento_online, name='pagamento_online'),
    path('gestao-recursos/', views.gestao_recursos, name='gestao_recursos'),
    path('biblioteca/', views.biblioteca, name='biblioteca'),
    path('laboratorios/', views.laboratorios, name='laboratorios'),
    path('transporte/', views.transporte, name='transporte'),
    path('dormitorios/', views.dormitorios, name='dormitorios'),
    path('infraestrutura/', views.infraestrutura, name='infraestrutura'),
    path('api/escolas/autocomplete/', views.escolas_autocomplete, name='escolas_autocomplete'),
    path('api/escolas/create/', views.escola_create_ajax, name='escola_create_ajax'),
    path('api/ano-academico/trocar/', views.trocar_ano_academico, name='trocar_ano_academico'),
    path('anos-academicos/', views.ano_academico_lista, name='ano_academico_lista'),
    path('anos-academicos/novo/', views.ano_academico_create, name='ano_academico_create'),
    path('anos-academicos/<int:pk>/editar/', views.ano_academico_edit, name='ano_academico_edit'),
    path('login/', views.login_view, name='login'),
    path('registro/', views.registro_view, name='registro'),
    path('logout/', views.logout_view, name='logout'),
    path('notificacoes/', views.notificacoes_view, name='notificacoes'),
    path('notificacoes/<int:notificacao_id>/marcar-lida/', views.marcar_notificacao_lida, name='marcar_notificacao_lida'),
    path('api/notificacoes/count/', views.get_notificacoes_count, name='notificacoes_count'),
    path('api/perfis-pendentes/count/', views.get_perfis_pendentes_count, name='perfis_pendentes_count'),
    path('pagamento-subscricao/', views.pagamento_subscricao_view, name='pagamento_subscricao'),
    path('renovar-subscricao/', views.renovar_subscricao_view, name='renovar_subscricao'),
    path('esqueci-senha/', views.esqueci_senha_view, name='esqueci_senha'),
    path('validar-otp/', views.validar_otp_view, name='validar_otp'),
    path('redefinir-senha/<str:token>/', views.redefinir_senha_email_view, name='redefinir_senha_email'),
    path('perfis-pendentes/', views.perfis_pendentes_view, name='perfis_pendentes'),
    path('atribuir-perfil/<int:perfil_id>/', views.atribuir_perfil_view, name='atribuir_perfil'),
    path('documentos/', views.gestao_documentos, name='gestao_documentos'),
    path('documentos/novo/', views.documento_criar, name='documento_criar'),
    path('documentos/<int:documento_id>/editar/', views.documento_editar, name='documento_editar'),
    path('documentos/<int:documento_id>/deletar/', views.documento_deletar, name='documento_deletar'),
    path('documentos/<int:documento_id>/visualizar/', views.documento_visualizar, name='documento_visualizar'),
    path('documentos/<int:documento_id>/pdf/', views.gerar_pdf_documento, name='gerar_pdf_documento'),
    path('documentos/<int:documento_id>/pdf/<int:inscricao_id>/', views.gerar_pdf_documento, name='gerar_pdf_documento_inscricao'),
    
    # URLs para Gestão de Utilizadores
    path('utilizadores/', views.listar_utilizadores, name='listar_utilizadores'),
    path('utilizadores/novo/', views.criar_utilizador, name='criar_utilizador'),
    path('utilizadores/<int:user_id>/editar/', views.editar_utilizador, name='editar_utilizador'),
    path('utilizadores/<int:user_id>/deletar/', views.deletar_utilizador, name='deletar_utilizador'),
    path('utilizadores/<int:user_id>/ativar/', views.ativar_utilizador, name='ativar_utilizador'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
